
name: My first workflow with gk actions

on: 
    push: 
        branches: ["main"]
    pull_request: 
        branches: ["main"]

jobs:
    build_and_push_docker_image:
        runs-on: ubuntu-latest
        permissions: 
            contents: read
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
            - name: Set Up JDK 11
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'temurin'
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 
            - name: Grant execute permission for gradlew 
              run: chmod +x gradlew 
            - name: Build with Gradlew Wrapper
              run: ./gradlew build



